### ISSUE TITLE
QuestionnaireResponse population with scoring

### ISSUE THREAD

**Issue by bennyhaeusler** [sujrd/faiadashu#138] opened 2024-08-27 07:14 UTC
The score (SDC feature) is not beeing calculated correctly, when an existing QuestionnaireResponse gets populated to fill the Questionnaire.

It can be reproduced, when running the example project, by filling the "Heart Failure Survey" (hf_instruments.json). The score is beeing calculated correctly when filling it the first time (see screenshot). 

If you complete and save the QuestionnaireResponse and then reload the survey again, the displayed total score only contains the value from the first question (it also displays total score twice) . The score item in the QuestionnaireResponse contains two valueDecimal (the score that got initially calculated and the value from the first question):
`{
    "linkId": "/hfcode-924-8",
    "text": "Overall summary score",
    "answer": [
        {
            "extension": [
                {
                    "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-unit",
                    "valueCoding": {
                        "display": "{score}"
                    }
                }
            ],
            "valueDecimal": 2
        },
        {
            "valueDecimal": 19
        }
    ]
}`

![filled](https://github.com/user-attachments/assets/34f625c8-402a-40ce-8415-7af7243b130c)
![filled-saved-reopened](https://github.com/user-attachments/assets/fd9a11af-1a7a-4ae7-86cc-5e4359dd63d9)
[questionnaire-response.json](https://github.com/user-attachments/files/16758079/questionnaire-response.json)

**Comment by fjwong** [comment] 2024-11-20 04:35
@bennyhaeusler Thank you for the bug report. We have been able to reproduce it on our side and are currently working on a fix.

It appears the problem is isolated to `hf_instruments.json` and other Questionnaires that may have an item with `questionnaire-unit` extension with `"valueCoding": { "display": "{score}" }`.

**Comment by fjwong** [comment] 2024-12-09 04:35
Fixed in #145

**Closed by fjwong** 2024-12-09 04:35 UTC
Labels: bug
